"""Legacy migration policy and rollback tests, without touching host services."""
import importlib.util
from pathlib import Path
import unittest
import tempfile
from types import SimpleNamespace
from unittest.mock import Mock, patch

spec = importlib.util.spec_from_file_location('legacy', Path(__file__).resolve().parents[1] / 'tools/migrate-legacy.py')
legacy = importlib.util.module_from_spec(spec)
spec.loader.exec_module(legacy)


class LegacyTests(unittest.TestCase):
    def test_zero_replaces_only_known_overlay(self):
        original = '[all]\ndtoverlay=dwc2,dr_mode=peripheral\ndtparam=audio=on\n'
        self.assertEqual(legacy.boot_contents(original, 'rpi-zero'), '[all]\ndtparam=audio=on\n')

    def test_generic_preserves_peripheral_boot_configuration(self):
        original = '[all]\ndtoverlay=dwc2,dr_mode=peripheral\n'
        self.assertEqual(legacy.boot_contents(original, 'generic'), original)

    def test_unknown_overlay_rejected(self):
        with self.assertRaises(ValueError):
            legacy.boot_contents('dtoverlay=dwc2,dr_mode=host\n', 'rpi-zero')

    def test_commented_overlay_preserved(self):
        original = '#dtoverlay=dwc2,dr_mode=host\n'
        self.assertEqual(legacy.boot_contents(original, 'rpi-zero'), original)

    def test_migration_success_and_failure_restore(self):
        for fail in (False, True):
            with self.subTest(fail=fail), tempfile.TemporaryDirectory() as directory:
                root = Path(directory)

                def target(path):
                    path = str(path)
                    return root / path.lstrip('/') if path.startswith('/') else Path(path)

                originals = {
                    '/etc/modules-load.d/usb-gadget.conf': 'g_ether\n',
                    '/etc/NetworkManager/dnsmasq-shared.d/90-rpi-usb-gadget-lease.conf': '# Autogenerated by rpi-usb-gadget\nquiet-dhcp\n',
                    '/boot/firmware/config.txt': '[all]\ndtoverlay=dwc2,dr_mode=peripheral\ndtparam=audio=on\n',
                    '/etc/NetworkManager/system-connections/usb.nmconnection': 'original USB profile\n',
                    '/etc/NetworkManager/system-connections/wifi.nmconnection': 'Wi-Fi must stay untouched\n',
                }
                for name, contents in originals.items():
                    path = target(name)
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(contents)
                profile = target('/etc/NetworkManager/system-connections/usb.nmconnection')
                calls = []

                def command(*args):
                    calls.append(args)
                    if args[:3] == ('nmcli', 'connection', 'modify'):
                        profile.write_text('autoconnect=false\n')
                    return ''

                def install_target(args):
                    self.assertFalse(target('/etc/modules-load.d/usb-gadget.conf').exists())
                    self.assertNotIn('dtoverlay=dwc2', target('/boot/firmware/config.txt').read_text())
                    if fail:
                        raise ValueError('injected installation failure')

                installer = SimpleNamespace(STATE=target('/var/lib/usb-cdc-ncm/install.json'),
                                            board_config=Mock(), network_config=Mock(), install=install_target)
                args = SimpleNamespace(board='rpi-zero', network='server', subnet='192.168.7.0/30')
                with patch.object(legacy, 'Path', side_effect=target), \
                     patch.object(legacy, 'BASE', target('/var/lib/usb-cdc-ncm')), \
                     patch.object(legacy, 'MODULES', target('/etc/modules-load.d/usb-gadget.conf')), \
                     patch.object(legacy, 'DNS', target('/etc/NetworkManager/dnsmasq-shared.d/90-rpi-usb-gadget-lease.conf')), \
                     patch.object(legacy, 'MASK', target('/etc/systemd/system/rpi-usb-gadget-ics.service')), \
                     patch.object(legacy, 'profiles', return_value=[('usb-uuid', profile)]), \
                     patch.object(legacy.shutil, 'which', return_value='/usr/sbin/rpi-usb-gadget'), \
                     patch.object(legacy.subprocess, 'run', return_value=SimpleNamespace(returncode=0)), \
                     patch.object(legacy, 'run', side_effect=command):
                    if fail:
                        with self.assertRaisesRegex(ValueError, 'injected'):
                            legacy.migrate(installer, args)
                        for name, contents in originals.items():
                            self.assertEqual(target(name).read_text(), contents)
                        self.assertIn(('systemctl', 'start', legacy.SERVICE), calls)
                    else:
                        legacy.migrate(installer, args)
                        self.assertEqual(profile.read_text(), 'autoconnect=false\n')
                        self.assertEqual(target('/etc/NetworkManager/system-connections/wifi.nmconnection').read_text(),
                                         originals['/etc/NetworkManager/system-connections/wifi.nmconnection'])
                    self.assertIn(('systemctl', 'mask', '--now', legacy.SERVICE), calls)
                    self.assertFalse(any('down' in call or 'off' in call for call in calls))
                    backups = list(target('/var/lib/usb-cdc-ncm').glob('legacy-backup-*'))
                    self.assertEqual(len(backups), 1)
                    self.assertEqual((backups[0] / 'completed').exists(), not fail)

    def test_non_usb_profile_is_rejected(self):
        def command(*args):
            if args[2] == 'UUID':
                return 'wifi-uuid'
            return {'connection.id': 'USB Gadget (shared)',
                    'connection.type': '802-11-wireless',
                    'connection.interface-name': 'wlan0'}[args[2]]
        with patch.object(legacy, 'run', side_effect=command):
            with self.assertRaisesRegex(ValueError, 'nonstandard legacy profile'):
                legacy.profiles()


if __name__ == '__main__':
    unittest.main()
