#!/usr/bin/env python3
"""Back up and retire the Raspberry Pi OS gadget configuration, then install NCM.

Keep the live g_ether link and its active NM connection until reboot. Never call
rpi-usb-gadget off: it disconnects USB and removes boot settings indiscriminately.
"""
import argparse
import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

BASE = Path('/var/lib/usb-cdc-ncm')
SERVICE = 'rpi-usb-gadget-ics.service'
MODULES = Path('/etc/modules-load.d/usb-gadget.conf')
DNS = Path('/etc/NetworkManager/dnsmasq-shared.d/90-rpi-usb-gadget-lease.conf')
MASK = Path('/etc/systemd/system') / SERVICE
NAMES = {'USB Gadget (client)', 'USB Gadget (shared)'}
OVERLAY = 'dtoverlay=dwc2,dr_mode=peripheral'


def run(*args):
    return subprocess.run(args, check=True, text=True, capture_output=True).stdout.strip()


def profiles():
    result = []
    for uuid in run('nmcli', '-g', 'UUID', 'connection', 'show').splitlines():
        name = run('nmcli', '-g', 'connection.id', 'connection', 'show', 'uuid', uuid)
        if name not in NAMES:
            continue
        kind = run('nmcli', '-g', 'connection.type', 'connection', 'show', 'uuid', uuid)
        iface = run('nmcli', '-g', 'connection.interface-name', 'connection', 'show', 'uuid', uuid)
        if kind != '802-3-ethernet' or iface != 'usb0':
            raise ValueError(f'Refusing to migrate nonstandard legacy profile {uuid}: {kind}, {iface}')
        filename = run('nmcli', '-g', 'GENERAL.FILENAME', 'connection', 'show', 'uuid', uuid)
        path = Path(filename)
        if not path.is_absolute() or not path.is_file() or path.is_symlink():
            raise ValueError(f'Cannot back up legacy profile {uuid}: {filename}')
        result.append((uuid, path))
    return result


def boot_contents(text, board):
    if board != 'rpi-zero':
        return text  # generic depends on the vendor's existing peripheral setup
    lines = text.splitlines(keepends=True)
    overlays = [line.strip() for line in lines if line.strip().startswith('dtoverlay=dwc2')]
    if any(line != OVERLAY for line in overlays):
        raise ValueError('Nonstandard dwc2 overlay; reconcile it before migration')
    return ''.join(line for line in lines if line.strip() != OVERLAY)


def migrate(install, args):
    # Once owned by NCM, updates must not retire its boot configuration again.
    if install.STATE.exists() or not shutil.which('rpi-usb-gadget'):
        install.install(args)
        return
    selected = profiles()
    edits = {}
    if MODULES.exists():
        modules = [s.strip() for s in MODULES.read_text().splitlines()
                   if s.strip() and not s.lstrip().startswith('#')]
        if modules != ['g_ether']:
            raise ValueError('Nonstandard usb-gadget.conf; refusing to remove unrelated modules')
        edits[MODULES] = None
    if DNS.exists():
        if 'Autogenerated by rpi-usb-gadget' not in DNS.read_text():
            raise ValueError('Nonstandard legacy dnsmasq snippet; reconcile before migration')
        edits[DNS] = None
    for path in (Path('/boot/firmware/config.txt'), Path('/boot/config.txt')):
        if path.exists():
            original = path.read_text()
            updated = boot_contents(original, args.board)
            if updated != original:
                edits[path] = updated
    # Validate the target board and basic dependencies before changing anything.
    model_path = Path('/proc/device-tree/model')
    model = model_path.read_text().rstrip('\0') if model_path.exists() else ''
    boot = next((p for p in (Path('/boot/firmware/config.txt'), Path('/boot/config.txt')) if p.exists()), None)
    install.board_config(args.board, model, boot, list(Path('/sys/class/udc').glob('*')))
    install.network_config('02:00:00:00:00:01', args.network, args.subnet)
    run('systemctl', 'cat', 'systemd-networkd.service')
    run('modprobe', '--dry-run', 'usb_f_ncm')
    if MASK.exists() or MASK.is_symlink():
        if not MASK.is_symlink() or os.readlink(MASK) != '/dev/null':
            raise ValueError(f'Custom service override: {MASK}')
    active = subprocess.run(['systemctl', 'is-active', '--quiet', SERVICE]).returncode == 0
    was_masked = MASK.is_symlink()
    BASE.mkdir(parents=True, exist_ok=True)
    backup = Path(tempfile.mkdtemp(prefix='legacy-backup-', dir=BASE))
    backup.chmod(0o700)
    paths = set(edits) | {path for _, path in selected}
    for path in paths:
        if path.is_symlink():
            raise ValueError(f'Refusing to rewrite symlink: {path}')
        dest = backup / path.relative_to(path.anchor)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, dest)
    (backup / 'manifest.json').write_text(json.dumps({
        'files': [str(p) for p in paths], 'service_active': active,
        'service_masked': was_masked, 'profiles': [u for u, _ in selected],
    }, indent=2) + '\n')
    print(f'Legacy backup: {backup}', flush=True)
    try:
        # Stop only the watcher; neither g_ether nor the active USB profile is stopped.
        run('systemctl', 'mask', '--now', SERVICE)
        for uuid, _ in selected:
            run('nmcli', 'connection', 'modify', 'uuid', uuid, 'connection.autoconnect', 'no')
        for path, content in edits.items():
            if content is None:
                path.unlink()
            else:
                path.write_text(content)
        install.install(args)
    except Exception:
        for path in paths:
            shutil.copy2(backup / path.relative_to(path.anchor), path)
        run('nmcli', 'connection', 'reload')
        if not was_masked:
            run('systemctl', 'unmask', SERVICE)
        if active:
            run('systemctl', 'start', SERVICE)
        print(f'Migration failed; legacy settings restored. Backup: {backup}', flush=True)
        raise
    (backup / 'completed').touch()
    print('Legacy gadget retired. Current USB link remains until reboot; do not run rpi-usb-gadget on.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--board', choices=['rpi-zero', 'generic'], required=True)
    parser.add_argument('--network', choices=['server', 'client'], required=True)
    parser.add_argument('--subnet', required=True)
    args = parser.parse_args()
    args.development, args.dry_run = True, False
    try:
        if os.name != 'posix' or os.geteuid() != 0:
            raise ValueError('Run as root on the target Linux board')
        spec = importlib.util.spec_from_file_location('installer', Path(__file__).with_name('install.py'))
        installer = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(installer)
        migrate(installer, args)
    except (ValueError, OSError, subprocess.CalledProcessError) as exc:
        parser.exit(1, f'Error: {exc}\n')


if __name__ == '__main__':
    main()
